// Package jwt_generation implements PayNet DuitNow Pay JWT (JSON Web Token) for API authentication.
// Ref: https://docs.developer.paynet.my/docs/duitnow-pay/integration/api-authentication
package jwt_generation

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Algorithm is the JWT signing algorithm. PayNet DuitNow Pay uses RS256.
type Algorithm string

const (
	RS256 Algorithm = "RS256"
)

func (a Algorithm) hash() crypto.Hash {
	return crypto.SHA256
}

// GenerateOptions holds parameters for JWT generation per PayNet DuitNow Pay API Authentication.
type GenerateOptions struct {
	// PrivateKey is the RSA private key used to sign the JWT.
	PrivateKey *rsa.PrivateKey
	// Algorithm is RS256 (default).
	Algorithm Algorithm
	// Issuer is the iss claim (BIC code assigned during onboarding).
	Issuer string
	// Subject is the sub claim (Merchant ID assigned during merchant registration).
	Subject string
	// JTI is the jti claim (UUID v4 generated by merchant).
	JTI string
	// Key is the custom "key" claim (Project ID assigned during onboarding).
	Key string
	// Data is the custom "data" claim: the request payload in body format (same body sent in the API request).
	Data interface{}
	// ValidDuration is how long the token is valid; must be within 1 hour (default 1 hour).
	ValidDuration time.Duration
}

// GenerateJWT builds a JWT token for a PayNet DuitNow Pay API request.
// Logic matches the doc's JavaScript sample: jwt.sign({ data, key }, privateKey, { algorithm: 'RS256', expiresIn, issuer, subject, jwtid }).
// Claims: iat, exp, iss, sub, jti, key, data. Place the result in the Authorization header as: "Bearer <token>".
func GenerateJWT(opts GenerateOptions) (string, error) {
	if opts.PrivateKey == nil {
		return "", fmt.Errorf("jwt: private key is required")
	}
	if opts.Algorithm == "" {
		opts.Algorithm = RS256
	}
	if opts.ValidDuration == 0 {
		opts.ValidDuration = 45 * time.Minute
	}
	if opts.Issuer == "" {
		opts.Issuer = "MBBEMYKL"
	}
	if opts.Subject == "" {
		opts.Subject = "M0000569"
	}
	if opts.JTI == "" {
		opts.JTI = "550e8400-e29b-41d4-a716-446655440000"
		// opts.JTI = uuid.New().String()
	}
	if opts.Key == "" {
		opts.Key = "A46548895"
	}

	now := time.Now().Unix()
	exp := time.Now().Add(opts.ValidDuration).Unix()

	// 1. JWT header (first segment of token, same as JS: algorithm + typ).
	// Token format = base64url(header).base64url(payload).base64url(signature)
	header := map[string]string{
		"alg": string(opts.Algorithm),
		"typ": "JWT",
	}
	headerJSON, err := json.Marshal(header)
	if err != nil {
		return "", fmt.Errorf("jwt: marshal header: %w", err)
	}
	headerB64 := base64.RawURLEncoding.EncodeToString(headerJSON)

	// 2. JWT claims: exp, iss, sub, jti, key, data (per PayNet Pay API Authentication); iat optional per sample generators.
	// data = request payload in body format (object). Use json.RawMessage(bodyBytes) so it is byte-identical to the HTTP body.
	body := map[string]interface{}{
		"iat":  now,
		"exp":  exp,
		"iss":  opts.Issuer,
		"sub":  opts.Subject,
		"jti":  opts.JTI,
		"key":  opts.Key,
		"data": opts.Data,
	}
	bodyJSON, err := json.Marshal(body)
	if err != nil {
		return "", fmt.Errorf("jwt: marshal body: %w", err)
	}
	bodyB64 := base64.RawURLEncoding.EncodeToString(bodyJSON)

	// 3. Sign signingInput = header + "." + payload
	signingInput := headerB64 + "." + bodyB64
	hashFn := opts.Algorithm.hash()
	hasher := hashFn.New()
	hasher.Write([]byte(signingInput))
	digest := hasher.Sum(nil)

	signature, err := rsa.SignPKCS1v15(rand.Reader, opts.PrivateKey, hashFn, digest)
	if err != nil {
		return "", fmt.Errorf("jwt: sign: %w", err)
	}
	sigB64 := base64.RawURLEncoding.EncodeToString(signature)

	return signingInput + "." + sigB64, nil
}

// VerifyOptions holds parameters for JWT verification (e.g. PayNet API response).
type VerifyOptions struct {
	// Token is the JWT (with or without "Bearer " prefix).
	Token string
	// PublicKey is the RSA public key (e.g. from PayNet) to verify the signature.
	PublicKey *rsa.PublicKey
	// Algorithm used in the token (RS256).
	Algorithm Algorithm
}

// VerifyJWT verifies a JWT from a PayNet DuitNow Pay API response.
// It checks the signature and expiration (exp). No payload hash check; Pay response JWTs do not use "ds".
func VerifyJWT(opts VerifyOptions) error {
	token := strings.TrimSpace(opts.Token)
	if strings.HasPrefix(strings.ToLower(token), "bearer ") {
		token = strings.TrimSpace(token[7:])
	}
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return fmt.Errorf("jwt: invalid token, expected 3 parts, got %d", len(parts))
	}

	headerB64, bodyB64, sigB64 := parts[0], parts[1], parts[2]
	signingInput := headerB64 + "." + bodyB64

	// Decode and verify signature
	sigBytes, err := base64.RawURLEncoding.DecodeString(sigB64)
	if err != nil {
		return fmt.Errorf("jwt: decode signature: %w", err)
	}
	hashFn := opts.Algorithm.hash()
	hasher := hashFn.New()
	hasher.Write([]byte(signingInput))
	digest := hasher.Sum(nil)
	if err := rsa.VerifyPKCS1v15(opts.PublicKey, hashFn, digest, sigBytes); err != nil {
		return fmt.Errorf("jwt: signature verification failed: %w", err)
	}

	// Decode payload and check exp
	bodyJSON, err := base64.RawURLEncoding.DecodeString(bodyB64)
	if err != nil {
		return fmt.Errorf("jwt: decode body: %w", err)
	}
	var claims struct {
		Exp int64 `json:"exp"`
	}
	if err := json.Unmarshal(bodyJSON, &claims); err != nil {
		return fmt.Errorf("jwt: parse body: %w", err)
	}
	if time.Now().Unix() > claims.Exp {
		return fmt.Errorf("jwt: token expired (exp=%d)", claims.Exp)
	}
	return nil
}
